# Rust formatting configuration for Bingo RETE Rules Engine
# This configuration uses only stable rustfmt features for compatibility

# Edition and basic style
edition = "2024"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Functions and control flow
fn_params_layout = "Tall"

# Strings and arrays
array_width = 80
attr_fn_like_width = 80
chain_width = 80
single_line_if_else_max_width = 50
struct_lit_width = 80
struct_variant_width = 80

# Error handling - important for rules engine reliability
force_explicit_abi = true

# Advanced formatting
match_block_trailing_comma = false