[package]
name = "bingo-api"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bingo"
path = "src/main.rs"

[dependencies]
# Core dependencies
bingo-core = { path = "../bingo-core" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Web framework
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }

# OpenAPI support
utoipa = { version = "4.0", features = ["axum_extras", "chrono", "uuid"] }
utoipa-swagger-ui = { version = "6.0", features = ["axum"] }
utoipa-rapidoc = { version = "3.0", features = ["axum"] }
utoipa-redoc = { version = "3.0", features = ["axum"] }

# Additional utilities
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
fnv = "1.0"

[dev-dependencies]
axum-test = "15.0"
futures = "0.3"

[features]
default = []