apiVersion: v1
kind: ConfigMap
metadata:
  name: bingo-config
  namespace: bingo
  labels:
    app: bingo-grpc
    component: config
data:
  # gRPC Configuration
  GRPC_LISTEN_ADDRESS: "0.0.0.0:50051"
  SERVICE_NAME: "bingo-grpc-api"
  SERVICE_VERSION: "1.0.0"
  BINGO_ENVIRONMENT: "production"
  
  # Logging Configuration
  RUST_LOG: "info"
  LOG_FORMAT: "json"
  
  # OpenTelemetry Configuration
  OTEL_SERVICE_NAME: "bingo-grpc"
  OTEL_SERVICE_VERSION: "1.0.0"
  OTEL_RESOURCE_ATTRIBUTES: "service.name=bingo-grpc,service.version=1.0.0,deployment.environment=production"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector:14268"
  
  # Performance Tuning
  WORKER_THREADS: "4"
  MAX_CONCURRENT_STREAMS: "1000"
  KEEPALIVE_TIME_MS: "30000"
  KEEPALIVE_TIMEOUT_MS: "5000"
  
  # Enhanced Monitoring
  MONITORING_ENABLED: "true"
  MONITORING_SAMPLING_INTERVAL: "60"
  PROMETHEUS_METRICS_ENABLED: "true"
  HEALTH_CHECK_INTERVAL: "30"
  
  # Security Configuration
  TLS_ENABLED: "true"
  MTLS_ENABLED: "false"
  AUTH_REQUIRED: "false"
  
  # Application Configuration
  config.toml: |
    [server]
    listen_address = "0.0.0.0:50051"
    max_connections = 1000
    request_timeout_ms = 30000
    
    [monitoring]
    enabled = true
    sampling_interval_seconds = 60
    max_historical_samples = 1440
    enable_prometheus_export = true
    enable_detailed_tracing = false
    
    [performance]
    worker_threads = 4
    max_concurrent_requests = 1000
    connection_pool_size = 10
    
    [cache]
    enabled = true
    provider = "redis"
    ttl_seconds = 3600
    max_size = 10000
    
    [security]
    tls_enabled = true
    cert_file = "/etc/ssl/certs/tls.crt"
    key_file = "/etc/ssl/private/tls.key"
    ca_file = "/etc/ssl/certs/ca.crt"