apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bingo-grpc-hpa
  namespace: bingo
  labels:
    app: bingo-grpc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bingo-grpc
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: grpc_server_handling_seconds
      target:
        type: AverageValue
        averageValue: "500m"  # 500ms average response time
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max
---
apiVersion: autoscaling/v2
kind: VerticalPodAutoscaler
metadata:
  name: bingo-grpc-vpa
  namespace: bingo
  labels:
    app: bingo-grpc
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bingo-grpc
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: bingo-grpc
      minAllowed:
        cpu: 250m
        memory: 512Mi
      maxAllowed:
        cpu: 4
        memory: 8Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits