apiVersion: v1
kind: Namespace
metadata:
  name: bingo
  labels:
    name: bingo
    purpose: bingo-rules-engine
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: bingo-quota
  namespace: bingo
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "10"
    services: "5"
    persistentvolumeclaims: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: bingo-limits
  namespace: bingo
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "250m"
      memory: "512Mi"
    type: Container