apiVersion: v1
kind: ServiceAccount
metadata:
  name: bingo-service-account
  namespace: bingo
  labels:
    app: bingo-grpc
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bingo-role
  namespace: bingo
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bingo-role-binding
  namespace: bingo
subjects:
- kind: ServiceAccount
  name: bingo-service-account
  namespace: bingo
roleRef:
  kind: Role
  name: bingo-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bingo-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/metrics"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bingo-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: bingo-service-account
  namespace: bingo
roleRef:
  kind: ClusterRole
  name: bingo-cluster-role
  apiGroup: rbac.authorization.k8s.io