apiVersion: v1
kind: Secret
metadata:
  name: bingo-secrets
  namespace: bingo
  labels:
    app: bingo-grpc
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  REDIS_PASSWORD: ""  # echo -n 'your-redis-password' | base64
  DATABASE_URL: ""    # echo -n 'your-database-url' | base64
  API_KEY: ""         # echo -n 'your-api-key' | base64
  JWT_SECRET: ""      # echo -n 'your-jwt-secret' | base64
---
apiVersion: v1
kind: Secret
metadata:
  name: bingo-tls-certs
  namespace: bingo
  labels:
    app: bingo-grpc
type: kubernetes.io/tls
data:
  # TLS certificate and key - generate using cert-manager or provide manually
  tls.crt: ""  # Base64 encoded certificate
  tls.key: ""  # Base64 encoded private key
  ca.crt: ""   # Base64 encoded CA certificate
---
# Example: Using cert-manager for automatic TLS certificate management
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: bingo-tls
#   namespace: bingo
# spec:
#   secretName: bingo-tls-certs
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
#   dnsNames:
#   - grpc.yourdomain.com
#   - bingo.yourdomain.com