[package]
name = "bingo-performance-test"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
bingo-core = { path = "../bingo-core" }
