name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run performance tests nightly at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual triggering of performance tests

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  # Essential checks - always run (ZERO tolerance for failures)
  quality:
    name: Code Quality & Fast Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Check formatting (ZERO tolerance)
      run: cargo fmt --check

    - name: Run clippy (ZERO warnings tolerance)
      run: cargo clippy --workspace --all-targets -- -D warnings

    - name: Check compilation across workspace
      run: cargo check --workspace --all-targets

    - name: Run all quality tests (excludes performance tests)
      run: cargo test --workspace
      env:
        RUST_LOG: info

  # Performance validation - CI-appropriate scale only
  performance:
    name: Performance Validation (CI Scale)
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-release-cargo-${{ hashFiles('**/Cargo.lock') }}

    # Run CI-appropriate scaling tests (100K, 200K facts)
    - name: Run CI-appropriate scaling tests
      run: cargo test --package bingo-core --test scaling_validation_test --release
      env:
        RUST_LOG: info

    # Optionally run a few representative performance tests
    - name: Run sample performance tests
      run: |
        cargo test --release test_calculator_cache_performance_improvement -- --ignored
        cargo test --release test_mixed_operations_performance -- --ignored
      continue-on-error: true  # Don't fail CI if performance tests timeout

  # Comprehensive performance validation - manual trigger or nightly
  performance-full:
    name: Full Performance Test Suite
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-performance-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run all performance tests
      run: cargo test --release -- --ignored
      timeout-minutes: 30
      env:
        RUST_LOG: info

    - name: Run heavy scaling tests (500K, 1M facts)
      run: cargo test --package bingo-core --test scaling_validation_test --ignored --release
      timeout-minutes: 15
      env:
        RUST_LOG: info

    - name: Generate performance report
      run: |
        echo "## Performance Test Results" > performance-report.md
        echo "- Full performance test suite completed successfully" >> performance-report.md
        echo "- Heavy scaling tests (500K, 1M facts) completed" >> performance-report.md
        echo "- All enterprise performance targets validated" >> performance-report.md

  # Security audit - only on main branch pushes to reduce resource usage
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Run security audit
      run: cargo audit

  # Coverage - only on main branch to reduce CI load
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: llvm-tools-preview

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov

    - name: Generate code coverage (exclude heavy tests)
      run: cargo llvm-cov --lib --lcov --output-path lcov.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: lcov.info
        fail_ci_if_error: false  # Don't fail CI on coverage issues

  # Release validation - only on main branch
  release-check:
    name: Release Check
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Verify release build
      run: cargo build --release --verbose

    - name: Run explain command
      run: cargo run --release --bin bingo explain


